[[redirects]]
from = "terrapreta.xyz/*"
to = "https://terrapreta.it/:splat"
status = 308
force = true

[[redirects]]
from = "www.terrapreta.xyz/*"
to = "https://terrapreta.it/:splat"
status = 308
force = true